### PR TITLE
add HAL to deployment, ship with CMakeLists file

### PR DESCRIPTION
**Pull request by oKermorgant**
Hi, 

When trying to use the `deployment` branch it seems that the `hal` folder is needed in `ping-device.cpp`.
This PR adds this folder to the branch, and also comes with a `CMakeLists.txt` to compile the whole deployment library.

### CODE REVIEW

**Comment by incebellipipo** [comment]
This issue is important but I think the solution should be different.
This repository uses Travis ci tool. Those lines should be modified I guess. Further comments are required from the authors.

https://github.com/bluerobotics/ping-cpp/blob/0e2b6599e1c9e0b593851af807c14ee6c270399d/tools/travis-ci-script.sh#L20-L21

**Comment by patrickelectric** [comment]
Hi @incebellipipo your approach is correct, it should be something closer to it.

**Review by patrickelectric — CHANGES_REQUESTED** [review]
@oKermorgant, can you do as explained on this comment ?
https://github.com/bluerobotics/ping-cpp/pull/35#issuecomment-998237292

**Comment by oKermorgant** [comment]
Hi, 
Sorry I have no experience with Travis CI and do not see how the branches are setup with regards to CI.

**Comment by incebellipipo** [comment]
We can turn this issue into a draft. I can take it on from now.

**Comment by incebellipipo** [comment]
I've made some changes but it should be discussed fairly.
The changes I propose is in [this repository](https://github.com/GSO-soslab/ping-cpp)

The resulting "deployment" branch looks like [this](https://github.com/GSO-soslab/ping-cpp/tree/deployment).

Those lines did the trick:
- https://github.com/GSO-soslab/ping-cpp/blob/7a912683d42e8f6a3e75aec62d494e081ab7e162/tools/travis-ci-script.sh#L20
- https://github.com/GSO-soslab/ping-cpp/blob/7a912683d42e8f6a3e75aec62d494e081ab7e162/tools/travis-ci-script.sh#L25

This repository includes commit 6a9db50 as well. [Here](https://github.com/GSO-soslab/ping-cpp/commit/6a9db504d82b27ca257170a666562361bdddda19) you can check.

However, I noticed that system continues to complain since generators are also not included in the deployment branch. Including generator python scripts would defy the very reason of having a "deployment" branch I thought. So I change the CMake logic a bit so that if the generated files are there it doesn't conduct the generation step. Proposed changes:
- https://github.com/GSO-soslab/ping-cpp/blob/7a912683d42e8f6a3e75aec62d494e081ab7e162/src/device/CMakeLists.txt#L4-L16
- https://github.com/GSO-soslab/ping-cpp/blob/7a912683d42e8f6a3e75aec62d494e081ab7e162/src/message/CMakeLists.txt#L7-L22
However, this deserves their own issue or PR.

**Comment by incebellipipo** [comment]
Checkout PR https://github.com/bluerobotics/ping-cpp/pull/39

**Comment by ES-Alexander** [comment]
Work continued in #39

**Pull request closed without merging**
